profile = "jinja"

ignore = "H031"

indent = 2
use_gitignore = true

close_void_tags = false
format_attribute_template_tags = true

indent_css = 2
indent_js = 2

max_attribute_length = 70

format_css = true
format_js = true
